language: php

# run tests on php 5.4 as it's the main supported version, and we need min 5.4 for integrated web server
php:
  - 5.4

# list of paths to execute
env:
  - TEST_SUIT="@eZDemoBundle"
#  - TEST_SUIT="vendor/ezsystems/demobundle/EzSystems/DemoBundle/Features/"


# test only master (+ Pull requests)
branches:
  only:
    - master

# install sahi and start x
before_install:
  - wget -nv -O sahi_20130429.zip "http://downloads.sourceforge.net/project/sahi/sahi-v44/sahi_20130429.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fsahi%2Ffiles%2Fsahi-v44%2F&ts=1376728867&use_mirror=garr"
  - unzip -o sahi_20130429.zip -d  ~
  - rm sahi_20130429.zip
  - sudo chmod +x ~/sahi/bin/sahi.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# setup requirements for running tests
# apache, eZ Publish legacy, database, sahi
before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS behattestdb;" -uroot
  - composer install --dev --prefer-dist --no-scripts
  - ./bin/.travis/prepare_legacy.sh
#  - ./bin/.travis/configure_apache2.sh
  - composer run-script --dev post-install-cmd
  - php ezpublish/console --env=behat assetic:dump
  - php ezpublish/console --no-interaction --env=behat ezpublish:test:init_db
#  - php ezpublish/console --no-interaction --env=behat server:run -r ../bin/.travis/ezrouter_behat.php localhost:8000 --process-isolation &
  - cp -f bin/.travis/sahi/browser_types.xml-dist ~/sahi/userdata/config/browser_types.xml
  - cd ~/sahi/bin
  - sh -e ./sahi.sh &
  - cd - && cd web/
  - php -S localhost:8000 ../bin/.travis/ezrouter.php &
  - cd ..
  - sleep 4
# Debug
  - curl --get "http://localhost:8000/"

# execute phpunit as the script command
script: "bin/behat $TEST_SUIT"

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
